<div class="jumbotron">
    <div class="row">
        <?php
            foreach ($this->flashMessenger()->getMessages() as $message) {
            echo "<span class='label label-success'>" . $message . "</span>";
            }

            foreach ($this->flashMessenger()->getErrorMessages() as $message) {
            echo "<span class='label label-danger'>" . $message . "</span>";
            }
        ?>
        <div class="col-md-12">
            <h2>Welcome to LOCK, guest</h2>
            <p>Please authorize yourself </p>
        </div>
    </div>
</div>
