<?php
$title = 'Add new user';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('security'));
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo '<br>';
echo $this->formRow($form->get('password'));
echo '<br>';
echo $this->formRow($form->get('role'));
echo '<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

