<h1><?= $this->escapeHtml('Edit user permissions') ?></h1>

<div class="row">
    <div class="col-md-2">
        <h4>Username:</h4>
    </div>
    <div class="col-md-2">
        <h4><?= $this->user['username'] ?></h4>
    </div>
    <div class="col-md-2">
        <h4>Role:</h4>
    </div>
    <div class="col-md-2">
        <h4><?= $this->user['role'] ?></h4>
    </div>
</div>
<?php if ($this->doors): ?>
    <form method="POST" action="<?= $this->url('user', ['action' => 'save']) ?>" name="savePermissions">
    <input type="hidden" name="userId" value="<?= $this->user['id'] ?>">
    <table class="table">
        <thead>

        </thead>
        <tbody>
        <?php foreach ($this->doors as $door): ?>
            <tr>
                <td><input type="checkbox" name="doorIds[]" value="<?= $door['id'] ?>"</td>
                <td><?= $door['alias'] ?></td>
                <td><?= $door['description'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <input type="submit" class="btn btn-primary" name="savePermissions" value="Save">
    </form>
<?php endif; ?>
